const ARTIFACT_DATA = 'ARTIFACT_DATA'
const FLOW_DESIGNER = 'FLOW_DESIGNER'
const REMOVE_FLOW_DESIGNER = 'REMOVE_FLOW_DESIGNER'
const REMOVE_ARTIFACT = 'REMOVE_ARTIFACT'
const OPEN_CHARTS = 'open-chart'
const CLOSE_CHARTS = 'close-chart'
const INIT_PARAMS = 'init-params'
const TOGGLE_COLUMN_MENU = 'toggle-column-menu'
const HIDE_COLUMN_MENU = 'hide-column-menu'
const UPDATE_XARRAY_DIM = 'update-xarray-dim'
const CONVERT_TO_XARRAY = 'convert-to-xarray'
const GET_COMMENTS = 'GET_COMMENTS'
const REMOVE_COMMENTS = 'REMOVE_COMMENTS'
const TOUR_OPEN = 'OPEN_TOUR'
const ARTIFACT_LIST = 'ARTIFACT_LIST'
const REFRESH_ARTIFACT_LIST = 'REFRESH_ARTIFACT_LIST'

const FOLDER_LIST = 'FOLDER_LIST'
const FOLDER_ARTIFACT_LIST = 'FOLDER_ARTIFACT_LIST'

const RECENT_ARTIFACT = 'RECENT_ARTIFACT'

export {
    REFRESH_ARTIFACT_LIST,
    FOLDER_ARTIFACT_LIST,
    FOLDER_LIST,
    ARTIFACT_LIST,
    TOUR_OPEN,
    ARTIFACT_DATA,
    FLOW_DESIGNER,
    REMOVE_ARTIFACT,
    REMOVE_FLOW_DESIGNER,
    OPEN_CHARTS,
    CLOSE_CHARTS,
    INIT_PARAMS,
    TOGGLE_COLUMN_MENU,
    HIDE_COLUMN_MENU,
    UPDATE_XARRAY_DIM,
    CONVERT_TO_XARRAY,
    GET_COMMENTS,
    REMOVE_COMMENTS,
    RECENT_ARTIFACT
}
